### PR TITLE
Customization of Swagger page template

### PR DESCRIPTION
**Pull request by jennifergarcia**
Added the following customizations in the SwaggerBundleConfiguration:
1)  Added a SwaggerViewConfiguration to contain all the properties related to the template file.  In the configuration you have the ability to set:
   * the template file so you can add minor customizations and styling
   * the title that shows in the HTML header
   * hiding the API json file selector
   * hiding the auth input boxes
2) Moved the validatorUrl property into the ViewConfiguration since it is only used in the template.

This should allow some customizations on Issue #20 
Allows you to add javascript code in a custom template for issue #25 to attach custom header information to each request.

### CODE REVIEW

**Comment by jennifergarcia** [comment]
I'm not sure why this is failing because it ran just fine locally.  If you have any ideas, let me know.

**Comment by jplock** [comment]
I tested this locally as well and all the tests passed, so looks good to merge 👍

**Comment by jennifergarcia** [comment]
Great, thanks!  Do you have an idea on when the never version build will be done so I can start using it? I did just realize that the test that failed did not have Selenium in the test name.  (Copy paste error).  I will have another small changeset to fix it.

**Comment by jplock** [comment]
@jennifergarcia what version of Dropwizare are you targeting?  `master` is currently built against `1.0.0-rc2`

**Comment by jennifergarcia** [comment]
We are on 9.2 right now but will soon be moving to 1.0, I was going to be updating when we got our changes in.  Were you guys waiting until the final rev of 1.0 to release?

**Comment by jplock** [comment]
Not particularly, I could probably create a 0.9.x maintenance branch and release from there, but feel free to commit into `master` for now and i'll work out the releases to create another 0.9.x release.

**Comment by jplock** [comment]
Just pushed up `0.9.2-2` with this change to Maven Central.

**Pull request merged**
