### PR TITLE
Upgrade to swagger-ui v3

### PR DESCRIPTION
**Pull request by jplock**
The swagger v3 UI is very different than the v2 version.  I'm not sure when it would be best to merge this in but my guess is v2 is no longer supported.

### CODE REVIEW

**Comment by jplock** [comment]
Thanks for reviewing @jadams74.  I need to update to the latest UI build.

**Comment by akraxx** [comment]
Jood job @jplock ! I will check the oauth2 part to see if everything is ok after the migration :)

**Comment by jplock** [comment]
@akraxx do you want to checkout this branch to see if its still working?  I haven't tested that part.

**Comment by akraxx** [comment]
Done in #83 , sorry had no time to do it before !

**Comment by rstorey** [comment]
I'm waiting for this to be merged so I can use it in my project without having to build from a fork and use a local maven repo (difficult with Docker deployments). Any chance of it getting merged into the main line soon?

**Comment by jplock** [comment]
@rstorey my main hesitation right now is that all of the integration tests are going to fail as soon as I merge this in (Travis doesn't execute those because they require Google Chrome right now).  So I either have to update the tests (which I don't have time at the moment to do), or remove them (since they were testing that swagger itself was mostly working, I'm leaning toward just removing them).

**Comment by rstorey** [comment]
Gotcha. My opinion: removing the tests is okay. Since what they're actually testing isn't the code of this project, but its underlying dependency, and if any of the tests were to fail, it would be indicative of a problem that isn't necessarily fixable within this project. Thanks for replying.

**Comment by jplock** [comment]
Ok let's do this

**Comment by rstorey** [comment]
Yay! Thank you!

**Pull request merged**
