### PR TITLE
Dropwizard 4

### PR DESCRIPTION
**Pull request by jarl-dk**
This PR also means using the new jakarta namespace

Related issues:
* https://github.com/smoketurner/dropwizard-swagger/issues/307
* https://github.com/smoketurner/dropwizard-swagger/issues/298

### CODE REVIEW

**Comment by jplock** [comment]
Can we split up this PR into phases? I’d like to see on that gets master building with they latest Dropwizard 2.1.x. Then I’m going to rename master to 2.1.x and create a 3.0.x branch where we can update to DW 3.0. Then we’ll do the same for 4.0 and the namespace changes.

**Comment by jarl-dk** [comment]
> Can we split up this PR into phases? I’d like to see on that gets master building with they latest Dropwizard 2.1.x. Then I’m going to rename master to 2.1.x and create a 3.0.x branch where we can update to DW 3.0. Then we’ll do the same for 4.0 and the namespace changes.

I'll see what I can do...

**Comment by jarl-dk** [comment]
I created a different PR for Dropwizard 3.0 at #310 
I have rebased this branch to be on top of the DW 3.0 branch

**Comment by jarl-dk** [comment]
The master already builds from the latest DW 2.x series.

**Comment by jplock** [comment]
`master` builds but `mvn verify` wasn't passing when I last tried it.  I need that to work to be able to publish to Maven Central.  Thank you for spending time on this.

**Comment by jarl-dk** [comment]
https://github.com/smoketurner/dropwizard-swagger/pull/311

You should setup some CI with github actions...

**Comment by jarl-dk** [comment]
@jplock : Can you make a release of this?

**Comment by jplock** [comment]
@jarl-dk I’ll review these PRs this weekend

**Comment by zUniQueX** [comment]
@jarl-dk Looks good overall. But some dependencies have to be updated additionally.

As a follow-up to the [discussion at Dropwizard](https://github.com/dropwizard/dropwizard/discussions/6920#discussioncomment-5523812) I've created a branch for the update myself to estimate the effort of the upgrade. The linked branch actually provides a full migration to Dropwizard 4.

The important updates include the Jersey bump to 3.0 and the Activation bump to 2.0. Jersey 2.x is EE 8 compatible, as well as Activation 1.2 is. Dropwizard 4 upgraded to EE 9, so we should stay consistent with the EE version here.

**Comment by jplock** [comment]
Just published v4.0.0-1 to Maven Central

**Comment by jarl-dk** [comment]
Thanks

**Pull request closed without merging**
