### PR TITLE
Upgrade to Dropwizard 2.0.0

### LINKED ISSUE #155: Version needed for Dropwizard 2.0.0
Dropwizard 2.0.0 is out there, and it cannot start with the latest version of dropwizard-swagger.
A new compatible version is necessary

### PR DESCRIPTION
**Pull request by jplock**
Fixes #155

All of the tests need to be updated to JUnit5 for this to compile and pass.  Unfortunately I'm not longer using this plugin, so if anyone would like to help with this effort, it would be very much appreciated.

### CODE REVIEW

**Comment by ankuagarwal** [comment]
@jplock I tried to use your yesterday's commit and fix the junit5 test migration, but I was stuck at 
```
java.lang.Exception: java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Predicate
```
I tried following `https://stackoverflow.com/a/22069399` but still no luck.

**Comment by jplock** [comment]
@ankuagarwal yea I saw that this morning, not sure where it's coming from yet.

**Comment by ankuagarwal** [comment]
Also I m not sure why i couldn't find junit5 dependency in dependency tree. In your commit you havent added it explicitly.

**Comment by jplock** [comment]
It's in the `dropwizard-pom` parent package I'm using.  I just added JUnit5 this morning as well and released a new version.

**Comment by DrMattFaulkner** [comment]
https://github.com/smoketurner/dropwizard-swagger/pull/159 Fixes the issues in this PR.

**Comment by DrMattFaulkner** [comment]
@jplock What's the ETA on a release of this?

**Comment by jplock** [comment]
@DrMattFaulkner will try to tag a release later tonight

**Comment by DrMattFaulkner** [comment]
Excellent. Thank you.

**Comment by jplock** [comment]
It's in maven central now - https://search.maven.org/artifact/com.smoketurner/dropwizard-swagger/2.0.0-1/jar

**Pull request merged**
