### PR TITLE
Updated freemarker template to match the updated index.html;

### PR DESCRIPTION
**Pull request by georgespalding**
Also adjusted query/header form and logic in index.ftl so that it worked with the latest swagger version.
The updated logic probably needs reviewing, there might be breaking changes...
Adjusted Auth tests to work with the changed form

### CODE REVIEW

**Comment by jplock** [comment]
I think I covered this in #14.  I've got a ton of pending changes in there including updating the template.

**Comment by jplock** [comment]
Thank you for the contribution, but I'm going to close this for now.  Would you mind submitting another PR to cleanup the javascript in the template related to the auth dropdown?  That would be a useful addition.

**Comment by georgespalding** [comment]
I'm happy to apply the changes to the index.ftl in #14
Provided you think it's useful.

**Comment by jplock** [comment]
I found the existing `change()` handler on `input_headerSelect` to be super ugly, so any improvement there would be great.  :)

**Pull request closed without merging**
