### PR TITLE
Dropwizard 0.9.1 support

### PR DESCRIPTION
**Pull request by jplock**

### CODE REVIEW

**Comment by akraxx** [comment]
Hi,

I took a look at this, you should replace 

``` java
    @GET
    @ApiOperation(OPERATION_DESCRIPTION)
    @Produces(MediaType.TEXT_PLAIN)
    public Response protectedDummyEndpoint(@ApiParam(hidden = true) @Auth String user) {
        return Response.ok().entity(user).build();
    }
```

by this : 

``` java
    @GET
    @ApiOperation(OPERATION_DESCRIPTION)
    @Produces(MediaType.TEXT_PLAIN)
    public Response protectedDummyEndpoint(@ApiParam(hidden = true) @Auth PrincipalImpl user) {
        return Response.ok().entity(user.getName()).build();
    }

```

in the `AuthResource` class.

Header are missing in the `TestAuthenticator` : https://travis-ci.org/smoketurner/dropwizard-swagger/jobs/90530978#L699

I hope it will help you :)

**Comment by jplock** [comment]
Thanks for your help @akraxx !

**Comment by akraxx** [comment]
You're welcome!

**Comment by jplock** [comment]
I just pushed up a `dropwizard-swagger-0.9.1-1` snapshot build to Maven central if you'd like to give it a go.

**Comment by akraxx** [comment]
Working well for me on a `dropwizard 0.9.1`

**Pull request merged**
