### PR TITLE
Added the posibility to configure the contextRoot

### PR DESCRIPTION
**Pull request by eciuca**
Added support for specifying the contextRoot where the application runs inside the container

### CODE REVIEW

**Comment by jplock** [comment]
Can we make this against master so it can support Dropwizard 1.x as well?

**Comment by eciuca** [comment]
Does travis always fail on jdk7 ? I only added a String

**Comment by eciuca** [comment]
Please, let me analyze the problem more because I'm not convinced the solution is good. Don't merge them yet. Thanks!

**Comment by jplock** [comment]
My main goal for this library is to keep it as turn-key as possible with minimal configuration.  I'd prefer if it just worked out of the box without having to configure anything.  If that's at all possible with this issue.  Thanks for looking into it.

**Comment by jplock** [comment]
@eciuca can we add some tests for this and fix whatever is causing travis to fail?  I'm very tempted to rip out all of the swagger tests we have as they are very fragile and the goal of this package is not to test swagger, but to test the bundle.

**Comment by eciuca** [comment]
I have tried on multiple machines. But I think I need an older version of firefox or something, because I can't run the tests (it doesn't send the url to the browser correctly). I have seen on the internet that it might be because of a Firefox update but I'm not really used to selenium and Firefox. I don't know if you have time to check the problem with selenium. I'll try to look more when I have time.

**Comment by jplock** [comment]
I'll merge this in but I won't be creating any more 0.9.x releases.  The tests in this project were very fragile before and required FireFox which I don't use.

**Comment by eciuca** [comment]
Can you please release this one? I have it as a project dependency and I have been using a local snapshot until now. I have changed the driver to Chrome, I don't know if you noticed. Thank you!

**Comment by jplock** [comment]
I'll try it out later tonight.  Thanks.

**Pull request merged**
